version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - intrange
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - godox
    - interfacebloat
    - lll
    - mnd
    - musttag
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    goconst:
      min-len: 5
      min-occurrences: 5
    gosec:
      excludes:
        - G601
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - (or|er)$
        - bigquery.DB
        - snowflake.SfClient
        - postgres.PgClient
        - mssql.MsClient
        - databricks.Client
        - athena.Client
        - duckdb.DuckDBClient
        - clickhouse.ClickHouseClient
        - tea.Model
        - driver.Rows
        - driver.Row
        - driver.Batch
    maintidx:
      under: 3
    nestif:
      min-complexity: 10
    revive:
      rules:
        - name: unexported-return
          disabled: true
    testifylint:
      enable:
        - bool-compare
        - compares
        - empty
        - error-is-as
        - error-nil
        - expected-actual
        - float-compare
        - len
        - suite-dont-use-pkg
        - suite-extra-assert-call
        - suite-thelper
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
        path: pkg/connection/connection.go
      - linters:
          - dupl
          - gosec
        path: (.+)_test.go
    paths:
      - vendor
      - .git
      - .idea
      - dist
      - .github
      - resources
      - bin
      - internal/data
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - .git
      - .idea
      - dist
      - .github
      - resources
      - bin
      - internal/data
      - third_party$
      - builtin$
      - examples$
